### ISSUE TITLE
[Feature Request] Support scatter_mul (as the one from torch-scatter 1.4.0)

### ISSUE THREAD

**Issue by vdecaro** [rusty1s/pytorch_scatter#151]
Hi @rusty1s , first of all thank your for your excellent job with this library.

I was wondering if the current version of the library still supports a function as scatter_mul from version 1.4.0 (unfortunately I cannot simply install version 1.4.0 because I have some dependencies on other functions from 2.0.5).  
I don't know if I am doing something wrong or, simply, I'm not finding it, but in case would it be possible to add a scatter_mul function to the current version of the library?

Thank you very much.

**Comment by rusty1s** [comment]
Yes, `scatter_mul` got removed in the `2.0.0` rewrite of the package, but I have plans to add it back in. Please have some patience :)

**Comment by zhanjiezhu** [comment]
I'm also looking for this scatter_mul, looking forward to have it back in latest version!

**Comment by zhanjiezhu** [comment]
Hi @rusty1s, I'm wondering if you know how much faster it is to use `scatter_mul` instead of a for loop in GPU? I tried to install 1.4.0 on my GPU server but it didn't work out, and when I tested it on my laptop with CPU it's running slower than a simple for loop. In my use case, I only need to do forward and I don't need gradients etc., if you know there are other alternatives that can do similar as `scatter_mul`, I would really appreciate if you could shed some light on this. Thanks!

**Comment by rusty1s** [comment]
This is hard to say. In case you have a very small output dimension with a lot of indices pointing to the same value, a simple for-loop might be even faster. In general, runtimes of `scatter_mul` should be comparable to `scatter_add`, so it might be best to conduct some tests with `scatter_add` to verify.

The reason CPU implementation might be slower is because of poor CPU multi-threading, which I have also plans to work on.

**Comment by jianhao2016** [comment]
Hi @rusty1s , I'm also looking for the same function with backward supports. Do you have any plan on which version it will come back?

**Comment by zjfstart** [comment]
Hello, why can't I install torch_scatter ==1.4.0 under Windows? I want to use the scatter_sub() function, but I can successfully install torch_scatter==2.0.0 or more, but it doesn't have the scatter_sub() function. Do you have any solution?

**Comment by rusty1s** [comment]
You can use `scatter_add` with `-x` as input.

**Comment by rusty1s** [comment]
I just added `scatter_mul` back into the master branch!
