### ISSUE TITLE
scatter_median?

### ISSUE THREAD

**Issue by justanhduc** [rusty1s/pytorch_scatter#227]
Hi. I need a `scatter_median` and am trying to develop based on your wonderful CUDA implementations. However, afaik all scatter methods here use atomic update, while to get median, it needs to gather and sort (or is there any way I'm not aware of?), which is not very straight forward to me how I can utilize your codes. Do you have any suggestion regarding this problem? Thanks alot!

**Comment by rusty1s** [comment]
You are right that this is not straightforward to add as a `scatter` operation, since each thread will process entries in isolation. This is probably best implemented as a `segment_csr` kernel, in which the indices pointing to the same output are ordered, see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/csrc/cuda/segment_csr_cuda.cu#L62-L95).

**Comment by justanhduc** [comment]
Thanks for the suggestion. I will check it out.

**Comment by aGIToz** [comment]
@justanhduc are you ready with this feature ? Can I try it ? I am in dire need of this feature! Best of luck !

**Comment by guicho271828** [comment]
Check out Fast k-Selection Algorithms for Graphics Processing Units
TOLU ALABI, JEFFREY D. BLANCHARD, BRADLEY GORDON, and RUSSEL STEINBACH
[12acm-alabi.pdf](https://github.com/rusty1s/pytorch_scatter/files/11168509/12acm-alabi.pdf)

**Comment by rusty1s** [comment]
We also have an implementation of this directly in PyG, see [here](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.aggr.MedianAggregation.html#torch_geometric.nn.aggr.MedianAggregation).
