### ISSUE TITLE
Availability on conda-forge

### ISSUE THREAD

**Issue by sarthakpati** [rusty1s/pytorch_scatter#235]
Hi,

Thank you for this project!

Would it be possible to make this available on conda-forge so that it could be combined as a requirement for other packages?

I have made a baseline ready: https://github.com/conda-forge/torch-scatter-feedstock

But it would be great if you could contribute your recipe there and perhaps become a maintainer? 

Cheers,
Sarthak

**Comment by rusty1s** [comment]
Thanks for reaching out. We have already started that discussion [here](https://github.com/rusty1s/pytorch_geometric/issues/2790). I think one major limitation in order to do that is that PyTorch itself recommends installing via their own `-c pytorch` channel, and I build my extensions against the official package from PyTorch rather than the `-c conda-forge` alternative.

**Comment by sarthakpati** [comment]
Moving discussion there.
