### ISSUE TITLE
Deploying heroku with requirements.txt

### ISSUE THREAD

**Issue by kshitijgundale** [rusty1s/pytorch_scatter#288]
I am trying to deploy a flask app to Heroku which has torch-scatter as dependency. Several issues mention this problem, in one of which you suggested to install torch before installing torch-scatter but I am not sure how to achieve that with a single requirements.txt.  
```
× python setup.py egg_info did not run successfully.
remote:          │ exit code: 1
remote:          ╰─> [6 lines of output]
remote:              Traceback (most recent call last):
remote:                File "<string>", line 2, in <module>
remote:                File "<pip-setuptools-caller>", line 34, in <module>
remote:                File "/tmp/pip-install-sngorvor/torch-scatter_c1e460d87e7942178ec794a31c37a08b/setup.py", line 8, in <module>
remote:                  import torch
remote:              ModuleNotFoundError: No module named 'torch'
remote:              [end of output]
```

**Comment by rusty1s** [comment]
It is only possible to install `torch` and `torch-scatter` within a single `requirements.txt` file if you make use of our pre-built wheels. If you install `torch-scatter` from source, you will need to import `torch` in order to do so.

An example of defining such a `requirements.txt` file can be found [here](https://github.com/pyg-team/pytorch_geometric/blob/master/docs/requirements.txt).

**Comment by kshitijgundale** [comment]
Worked like a charm, thanks a lot.
