### ISSUE TITLE
How to install torch-scatter=1.3.2 ? 

### ISSUE THREAD

**Issue by Alex-bd** [rusty1s/pytorch_scatter#374]
How to install torch-scatter=1.3.2 in an environment with torch=1.3.0? I tried pip install and source code compilation, but both reported errors.

**Comment by rusty1s** [comment]
It would be a bit easier if you could upgrade to at least PyTorch 1.4, since starting from there, we added binaries for installation, see [here](https://data.pyg.org/whl/index.html). It's a bit hard to tell what is needed on your end to compile `torch-scatter==1.3.2` (it's now nearly 4 years old :)). Feel free to post the installation log with any errors and I can try to take a look.

**Comment by Alex-bd** [comment]
Thank you very much for your prompt response. My problem has been resolved due to an issue with the Cuda path, and it has been resolved. Thank you very much for letting me pay attention to the specific error message.
