### ISSUE TITLE
Installation failed on HPC

### ISSUE THREAD

**Issue by david-leon** [rusty1s/pytorch_scatter#82]
I'm trying to install `torch-scatter` on the logon node of our HPC cluster managed by Sun Grid Engine. the `$PATH` and `$CPATH` are set correctly, but error is raised `Found no NVIDIA driver on your system`, since GPU is only available on the work node, not the logon node of the HPC.
The following is the detailed error log:
[install_log.txt](https://github.com/rusty1s/pytorch_scatter/files/3873302/install_log.txt)

Is there any way to bypass this problem? B.T.W., cuda version of pytorch installs successfully.

**Comment by rusty1s** [comment]
Mh, this is difficult. PyTorch works for you since it is coming with its own CUDA binaries. We do not provide any binaries for PyG, so it cannot be installed with CUDA support without CUDA. Sadly, I do not have a real solution or recommendation for you. We are kinda limited by the PyTorch extension API in this case.

**Comment by david-leon** [comment]
I see, thank you for your help.
B.T.W., is there any plan/progress on merging pytorch-scatter into pytorch master branch?

**Comment by rusty1s** [comment]
Yes, there is an open issue [here](https://github.com/rusty1s/pytorch_scatter/issues/82#issuecomment-558422882).
